package com.zegocloud.uikit.prebuilt.livestreaming.core;

public enum ZegoMenuBarButtonName {
    TOGGLE_CAMERA_BUTTON,
    TOGGLE_MICROPHONE_BUTTON,
    SWITCH_AUDIO_OUTPUT_BUTTON,
    LEAVE_BUTTON,
    SWITCH_CAMERA_FACING_BUTTON,
    COHOST_CONTROL_BUTTON,
    ENABLE_CHAT_BUTTON,
    SCREEN_SHARING_TOGGLE_BUTTON,
    BEAUTY_BUTTON,
}
